version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  commit-workflow:
      jobs:
        - cypress/run:
            browser: electron
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
        - cypress/run:
            browser: electron
